// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znaevbzcuxcnqfpgskhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuYWV2YnpjdXhjbnFmcGdza2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDc2NDUsImV4cCI6MjA1ODgyMzY0NX0.0c6mLsYOhJuUeiEfRDv0BL71Db-9QZNmjjrcFBkGleg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);